### ISSUE TITLE
提案：PreactからReact(Next.js)への置き換え

### ISSUE THREAD

**Issue by hrdtbs** [MochiNoaProject/homepage#34]
反対意見がなく2,3人の方に同意してもらえたら、移行作業を私がします。

## モチベーション

- Preactのエコシステムが停滞気味であり、今後保守するのが面倒になると思われる
- PreactよりもReactの方が慣れている方が多いので、PRを投げやすくなるはず
- CSS Modulesの使用もあまりおすすめできない

**Comment by takanakahiko** [comment]
完全同意侍！ :ninja:
